#!/bin/sh

set -eux

cd $HOME
mkdir .vim
mkdir .vim/colors .vim/backup .vim/bundle .vim/undo
wget -nv https://raw.githubusercontent.com/Annigilator/Scripts/master/vim/xoria256-my.vim -O .vim/colors/xoria256-my.vim
wget -nv https://raw.githubusercontent.com/Annigilator/Scripts/master/vim/vimrc -O .vim/vimrc
git clone -q https://github.com/gmarik/Vundle.vim.git .vim/bundle/Vundle.vim
ln -fs $HOME/.vim/vimrc $HOME/.vimrc
