" <{[ Plugins declaration

set nocompatible  " Use Vim defaults instead of 100% vi compatibility
filetype off

set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()

" Let Vundle manage itself
Plugin 'gmarik/Vundle.vim'

" Python syntax and indents
Plugin 'python-mode/python-mode'
" Tags bar
Plugin 'majutsushi/tagbar'
" Code autocomplete
Plugin 'Valloric/YouCompleteMe'
" Code errors checking
Plugin 'scrooloose/syntastic'
" Fast fs tree navigation
Plugin 'scrooloose/nerdtree'
" Lean & mean status line
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
" Snippets support
Plugin 'SirVer/ultisnips'
" Git features
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'

call vundle#end()
filetype plugin indent on " required by Vundle
" ]}>

" <{[ Plugins settings

let g:tagbar_width = 35
let g:tagbar_indent = 1
let g:tagbar_left = 1
let g:tagbar_autofocus = 1
let g:tagbar_sort = 0
let g:tagbar_foldlevel = 0
let g:tagbar_map_openfold = '<Right>'
let g:tagbar_map_closefold = '<Left>'
" open tagbar automatically if filetype is supported
autocmd VimEnter * nested :call tagbar#autoopen(1)

let g:pymode_syntax = 1
let g:pymode_indent = 1
let g:pymode_motion = 1
let g:pymode_folding = 0
let g:pymode_rope = 0
let g:pymode_lint = 0
let g:pymode_run = 0
let g:pymode_virtualenv = 0

let g:ycm_confirm_extra_conf = 0
let g:ycm_key_list_select_completion = ['<Down>']
let g:ycm_key_list_previous_completion = ['<Up>']
let g:ycm_goto_buffer_command = 'vertical-split'
let g:ycm_show_diagnostics_ui = 0
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_min_num_of_chars_for_completion = 3
let g:ycm_min_num_identifier_candidate_chars = 2
let g:ycm_use_ultisnips_completer = 0

let g:syntastic_mode_map = {'mode': 'active'}
let g:syntastic_check_on_wq = 1
let g:syntastic_aggregate_errors = 1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_loc_list_height = 5
let g:syntastic_error_symbol = 'E'
let g:syntastic_style_error_symbol = 'SE'
let g:syntastic_warning_symbol = 'W'
let g:syntastic_style_warning_symbol = 'SW'
let g:syntastic_cpp_compiler = 'g++-4.9'
let g:syntastic_cpp_compiler_options = ' -std=c++11'
let g:syntastic_python_checkers = ['pylint', 'pycodestyle']
let g:syntastic_python_pylint_post_args = '--msg-template="{path}:{line}:{column}:{C}: {msg_id} {msg}" --disable=W0108,C0330'
let g:syntastic_python_pycodestyle_post_args = '--ignore=E501'

let g:UltiSnipsExpandTrigger = '<TAB>'
let g:UltiSnipsJumpForwardTrigger = '<TAB>'
let g:UltiSnipsJumpBackwardTrigger = '<S-TAB>'

let g:airline_theme = 'simple'
let g:airline_left_sep = '▶'
let g:airline_left_alt_sep = '❯'
let g:airline_right_sep = '◀'
let g:airline_right_alt_sep = '❮'
let g:airline_symbols = {}
let g:airline_symbols.linenr = '␤ '
let g:airline_symbols.branch = '⎇ '
let g:airline_symbols.readonly = 'RO'
let g:airline_symbols.whitespace = '☢ '
" ]}>

" <{[ Global settings

syntax on
set t_Co=256 " Force 256 colors
colorscheme molokai-my

set encoding=utf-8
set fileencodings=utf-8,cp1251,koi8-r

set viminfo='20,\"50  " read/write file .viminfo, store<=50 lines of registers
set history=50        " keep 50 lines of command line history
" Suffixes that get lower priority when doing tab completion for filenames.
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,
            \.ind,.idx,.ilg,.inx,.out,.toc

set ruler                 " Show the cursor position all the time
set number                " Show line numbers
set laststatus=2          " Always show the statusline
set colorcolumn=80        " Color 80 characters in line
hi ColorColumn ctermbg=234
"set textwidth=80         " 80 characters in line
set cursorline           " Highlight current line

set foldmethod=marker     " Folding based on markers
set foldmarker=<{[,]}>    " Folding marker
set foldtext=MyFoldText() " Text for closed folding

set listchars=tab:▸·,trail:·,extends:$,eol:↲

set hidden      " More native buffer behavior
set showcmd     " Show (partial) command in status line.
set showmatch   " Show matching brackets.
set ignorecase  " Do case insensitive matching
set incsearch   " Incremental search
"set autowrite  " Automatically save before commands like :next and :make

set wildignore=*/.git/*,*/.svn/*
set wildignore+=*.o,*.so,*.pyc
set wildmode=longest:full
set wildmenu

set shiftwidth=4
set tabstop=4
set softtabstop=4
set smarttab
set expandtab
set smartindent

set hlsearch    " Highlight search
set nowrapscan  " Don't wrap around EOF or BOF while searching
set suffixesadd=.pl,.pm,.yml,.yaml,.tyaml  " for `gf' (open file under cursor)

set backspace=indent,eol,start  " More powerful backspacing
set backupcopy=yes              " Keep a backup file
set backupdir=~/.vim/backup     " Backup file directory
if has("persistent_undo")
    set undofile                " Persistent undo
    set undodir=~/.vim/undo
endif
" ]}>

" <{[ KeyMap settings

nmap <F2> :YcmComplete GoToDeclaration<CR>
nmap <F3> :YcmComplete GoToDefinition<CR>
nmap <F4> :YcmCompleter GoToReferences<CR>

nmap <F5> :SyntasticCheck<CR>
nmap <F6> :SyntasticInfo<CR>
nmap <F7> :SyntasticReset<CR>

nmap <F8> :TagbarToggle<CR>

nmap > :lnext<CR>
nmap < :lprev<CR>

noremap <Leader>pc :pclose<CR>
noremap <Leader>lc :lclose<CR>
noremap <Leader>n :set number<CR>
noremap <Leader>nn :set nonumber<CR>
noremap <Leader>l :set list<CR>
noremap <Leader>nl :set nolist<CR>
" ]}>

" <{[ Functions

function! MyFoldText()
    let line = substitute(getline(v:foldstart), '[^[{<]*<{' . '[\s*', '', 'g')
    let n = v:foldend - v:foldstart + 1
    let foldtext = ">> " . line . " (" . n . " lines)"
    return foldtext . repeat(" ", winwidth(0) - len(foldtext))
endfunction
" ]}>
